version: '3.8' # req'd for `pmsipilot/docker-compose-viz` to understand.

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - MOZILLATTS_API_URL=http://mozillatts:5002/api/tts
    depends_on:
      - mozillatts
      - cache
  mozillatts:
    build: mozillatts
  cache:
    image: "redis:alpine"