version: '3.8' # req'd for `pmsipilot/docker-compose-viz` to understand.

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - MOZILLATTS_API_URL=http://mozillatts:5002/api/tts
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - mozillatts
      - cache
  mozillatts:
    build: mozillatts
  cache:
    image: "redis:alpine"
    volumes:
      - ./redis_conf:/usr/local/etc/redis